// apps/example/src/stories/Button.vue
<template>
  <v-btn
    type="button"
    :color="primary ? 'primary' : undefined"
    @click="emit('click')"
    :variant="variant"
    :size="size"
    >{{ label }}</v-btn
  >
</template>

<script lang="ts" setup>
import { computed } from "vue";

const props = defineProps<{
  label: string;
  primary?: boolean;
  size?: "x-small" | "small" | "default" | "large" | "x-large";
}>();

const emit = defineEmits<{ (e: "click"): void }>();

const variant = computed(() => (props.primary ? "flat" : "outlined"));
</script>

// turborepo/with-storybook/packages/ui/Button.tsx
import * as React from "react";

interface Props {
  primary?: boolean;
  size?: "small" | "large";
  label?: string;
}

export const Button = ({
  primary = false,
  label = "Boop",
  size = "small",
}: Props) => {
  return (
    <button
      style={{
        backgroundColor: primary ? "red" : "blue",
        fontSize: size === "large" ? "24px" : "14px",
      }}
    >
      {label}
    </button>
  );
};
